import AdminNav from "../components/AdminNav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <AdminNav />
        <div>{children}</div>
    </div>
  );
}
